name: Update Diagram
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Generate Diagram
      id: diagram
      uses: your-org/repo-visualizer@v1
      with:
        output_file: diagram.svg
        excluded_paths: dist,node_modules
        max_depth: 5
        file_colors: '{"md": "#ff0000"}'
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: diagram
        path: diagram.svg 